workflows:
  ios-build:
    name: iOS Build
    environment:
      groups:
        - ios # Grupo contendo as chaves e certificações necessárias para buildar no iOS
      xcode: latest
    scripts:
      - name: Set up Node.js
        script: |
          # Instalar a versão específica do Node.js
          nvm install 18
          nvm use 18
          npm install -g @ionic/cli
      - name: Install Dependencies
        script: |
          npm install --legacy-peer-deps
          npx cap sync ios
      - name: Build iOS App
        script: |
          cd ios/App
          # Construir o aplicativo iOS
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos clean build
      - name: Archive iOS App
        script: |
          cd ios/App
          # Arquivar o aplicativo iOS
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos archive -archivePath $CM_BUILD_DIR/App.xcarchive
      - name: Export IPA
        script: |
          # Criar o arquivo exportOptions.plist para exportar o IPA
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
          <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
          <plist version=\"1.0\">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>signingStyle</key>
            <string>automatic</string>
            <key>teamID</key>
            <string>YOUR_TEAM_ID</string>
          </dict>
          </plist>" > exportOptions.plist

          # Exportar o arquivo IPA
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
